import Head from 'next/head'
import { Content, Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import "./mobile.style.css";
import "@/hooks/smoothscroll";
import Header from "@/components/header";
import logo from "@/assets/planb-logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head> <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet" /> </Head>
      <body className={inter.className}>
        <main>
          
          <content>{children}</content>
        </main>
      </body>
    </html>
  );
}
